spring.output.ansi.enabled: always

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 1
  serviceUrl:
    defaultZone: http://localhost:8761


management:
  endpoints:
    web:
      exposure:
        include: "refresh"
  