spring.output.ansi.enabled: always


server:
    port: 8888

spring:
    profiles.active: default
    cloud:
        config:
            server:
                encrypt.enabled: false
                git:
                    uri: https://github.com/yongsang92/movieconfig
                    search-paths: koreaservice, japanservice
                